### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by jmayank23** [techytushar/ocr-date-extractor#1]
Is the app still active, I tried making a request but did not get any response. Does it require the image in a certain format? I did the following-
date_ocr = requests.post('https://ocr-date-extractor.herokuapp.com/extract_date', data={'image': img})
where img is a np array

**Comment by techytushar** [comment]
The app is up and working. It does not support image as numpy array. As mentioned in the readme, either you can send Base64 encoded image or directly the image file [https://github.com/techytushar/ocr-date-extractor#how-to-use](https://github.com/techytushar/ocr-date-extractor#how-to-use)
